spring:
  datasource:
    url: jdbc:mysql://localhost:3306/konkuk?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        #default_batch_fetch_size: 100
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace
  org.hibernate.orm.jdbc.bind: